class DashboardController < ApplicationController

  def index
    @productions = current_user&.productions
    
    # Generate waste data: Calculate total waste for each production process.
    @waste_data = @productions.map do |production|
      [production.process_name, production.production_raw_materials.sum { |prm| prm.raw_material.waste_rate * prm.quantity_used }]
    end

     # Generate CO2 data: Calculate total CO2 emissions for each production process.
    # For each production, sum the CO2 emissions generated by all raw materials used.
    @co2_data = @productions.map do |production|
      [production.process_name, production.production_raw_materials.sum { |prm| prm.raw_material.co2_per_kg * prm.quantity_used * prm.raw_material.waste_rate }]
    end

    @co2_colors = @productions.map.with_index do |production, index|
      "#"+("%06x" % (rand * 0xffffff)).to_s  # Generates a random hex color code.
    end
    
    # Combine data for waste and CO2 emissions into a single structure for each production process.
    # This creates an array of hashes, each containing the process name, waste quantity, and CO2 emissions.
    @combined_data = @productions.map do |production|
      waste_quantity = production.production_raw_materials.sum { |prm| prm.raw_material.waste_rate * prm.quantity_used }
      co2_emissions = production.production_raw_materials.sum { |prm| prm.raw_material.co2_per_kg * prm.quantity_used * prm.raw_material.waste_rate }

      { process: production.process_name, waste: waste_quantity, co2: co2_emissions }
    end
  
  end
  
end
